demoapp:
        monitoringNode: local
        sdaHandlerBaseUri: http://localhost:8089
        sdaHandlerRestartUri: /restartCollector
spring:
    application:
        name: sdaDemoApp
    datasource:
        url: jdbc:mysql://localhost:3306/twstats
        username: root
        password: admin
    jpa: 
        show-sql: true
        format-sql: true
        use-sql-comments: true
        hibernate:
                  ddl-auto: update
                  naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
                    hibernate:
                              dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 9000
