FORMAT: 1A
HOST: http://sda.example.instance

# sda

Sda is a simple set of api allowing adding hashtags on monitoring on Social
Data Aggregator and retrieve information on generated analytics.


## Group Add keys on monitoring

Resources related to how add keys on monitoring on Social Data Aggregator

## Add new hashtag on monitoring [/monitor/ht/{ht}]

### Add new ht on monitoring [POST]

+ Parameters
    + ht (String) - the hashtag to monitor from twitter

+ Response 200 (application/json)

        {
            "key": "#twitter",
            "onMonitoringFrom":"2015-09-01T22:13:13+02"
         }

## Group Gender Recognition Algorithm analytics 

Resources related on analytics result regarding Gender Recognition Algorithm

## Last data by hashtag [/gender/hts/{ht}/last]

### Get last data by hashtag [GET]
+ Parameters
    + ht (String) - The hashtag on which retrieve the analytics

+ Response 200 (application/json)

        {
            "ht": "#twitter",
            "createdAt":"2015-09-02T22:15:13+02",
            "numTWMales": 100,
            "numRtwMales": 0,
            "numReplyMales": 41,
            "numTWFemales": 10,
            "numRtwFemales": 40,
            "numReplyFemales": 4,
            "numTWPages": 20,
            "numRtwPages": 10,
            "numReplyPages": 24,
            "numTWUnknown": 20,
            "numRtwUnknown": 10,
            "numReplyUnknown": 24
         }


## History data by hashtag [/gender/hts/{ht}/history]

### Get history data by hashtag [GET]
+ Parameters
    + ht (String) - The hashtag on which retrieve the analytics

+ Response 200 (application/json)

        [
            {
                "ht": "#twitter",
                "createdAt":"2015-09-02T22:15:13+02",
                "numTWMales": 100,
                "numRtwMales": 0,
                "numReplyMales": 41,
                "numTWFemales": 10,
                "numRtwFemales": 40,
                "numReplyFemales": 4,
                "numTWPages": 20,
                "numRtwPages": 10,
                "numReplyPages": 24,
                "numTWUnknown": 20,
                "numRtwUnknown": 10,
                "numReplyUnknown": 24
            },
            {
                "ht": "#twitter",
                "createdAt":"2015-09-02T22:14:13+02",
                "numTWMales": 10,
                "numRtwMales": 20,
                "numReplyMales": 11,
                "numTWFemales": 1,
                "numRtwFemales": 0,
                "numReplyFemales": 24,
                "numTWPages": 10,
                "numRtwPages": 180,
                "numReplyPages": 4,
                "numTWUnknown": 2,
                "numRtwUnknown": 1,
                "numReplyUnknown": 2
            }
        ]

## Group last tweets

## Get last tweets [/tweets/{ht}{?numResults}]

### Get last tweets by hashtag [GET]

+ Parameters
    + ht (String) - The hashtag on which retrieve the analytics
    + numResults (int) - Number of expected results (5 -> last five results) 
 

+ Response 200 (application/json)

        [
            {
                "ht": "#twitter",
                "createdAt":"2015-09-02T22:14:13+02",
                "twData":{
                    "postId":1004324234,
                    "userId":474826,
                    "screenName": "testUser",
                    "profileImageUrl":"http://example.com/p.jpg",
                    "text": "sample tweet text",
                    "screenName": "testUser",
                }
            }
        ]

